apiVersion: v1
kind: Service
metadata:
  name: monitoring-app
  labels:
    app: monitoring-app
spec:
  selector:
    app: monitoring-app
  ports:
    - port: 80
      targetPort: 3000
      name: http